import Link from "next/link";
import { Search, Briefcase, Users, Sparkles } from "lucide-react";

export default function Home() {
  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-indigo-600 via-indigo-700 to-purple-800 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              Find Your Next
              <span className="block text-indigo-200">Career Opportunity</span>
            </h1>
            <p className="text-xl text-indigo-100 mb-8 max-w-2xl mx-auto">
              Connect with top employers across Africa and beyond. Tailored resumes, smart matching, seamless applications.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/jobs"
                className="inline-flex items-center justify-center gap-2 bg-white text-indigo-700 px-8 py-4 rounded-lg font-semibold hover:bg-indigo-50 transition"
              >
                <Search className="h-5 w-5" />
                Browse Jobs
              </Link>
              <Link
                href="/signup?type=employer"
                className="inline-flex items-center justify-center gap-2 border-2 border-white text-white px-8 py-4 rounded-lg font-semibold hover:bg-white/10 transition"
              >
                <Briefcase className="h-5 w-5" />
                Post a Job
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Why UmukoziHR Jobs?</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Part of the UmukoziHR ecosystem, built to connect African talent with global opportunities.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-xl shadow-sm">
              <div className="bg-indigo-100 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                <Sparkles className="h-6 w-6 text-indigo-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">AI-Powered Matching</h3>
              <p className="text-gray-600">
                Our intelligent matching engine connects you with the most relevant opportunities based on your skills and experience.
              </p>
            </div>
            <div className="bg-white p-8 rounded-xl shadow-sm">
              <div className="bg-indigo-100 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                <Briefcase className="h-6 w-6 text-indigo-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Tailor Integration</h3>
              <p className="text-gray-600">
                Apply with perfectly tailored resumes generated by UmukoziHR Tailor, optimized for each job description.
              </p>
            </div>
            <div className="bg-white p-8 rounded-xl shadow-sm">
              <div className="bg-indigo-100 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                <Users className="h-6 w-6 text-indigo-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Quality Employers</h3>
              <p className="text-gray-600">
                Connect with verified companies looking for exceptional talent. No spam, no scams, just real opportunities.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-indigo-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Take the Next Step?</h2>
          <p className="text-indigo-200 mb-8 max-w-2xl mx-auto">
            Join thousands of professionals finding their dream jobs through UmukoziHR Jobs.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/signup?type=candidate"
              className="inline-flex items-center justify-center bg-white text-indigo-900 px-8 py-4 rounded-lg font-semibold hover:bg-indigo-50 transition"
            >
              Create Your Profile
            </Link>
            <Link
              href="/signup?type=employer"
              className="inline-flex items-center justify-center border-2 border-white text-white px-8 py-4 rounded-lg font-semibold hover:bg-white/10 transition"
            >
              Start Hiring
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}